import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./session-provider";
const manrope = Manrope({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Athnen: Your AI-powered Intel Network",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
